version: '3'
   
services:
  npm:
    container_name: npm
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - ffvl-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
     - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ffvl-network

volumes:
  mongo-data:
    driver: local

networks:
  ffvl-network:
    driver: bridge