version: '3.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  npm:
    image: node:14
    container_name: npm
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "npm install && npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - kibana

volumes:
  esdata:
    driver: local