version: '3.8'

services:
  npm:
    image: node:14
    container_name: npm
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "npm install && npm run start"
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  esdata:
    driver: local
  mongo-data:
    driver: local